# Enfoque con Embeddings
Todo a embeddings (queries, sinopsis + año + director + keywords) --> 5 con mas similtud coseno (comparando queries vs sinopsis + año + director + keywords)

La estrategia consiste en representar tanto las películas como las preferencias de cada usuario en un espacio vectorial común, y recomendar las películas cuyo vector sea más similar al perfil del usuario.

1. unificar texto
2. embeddings con w2v o sentence transformer sobre texto y queries
3. similitud coseno text vs queries

In [4]:
!pip install datasets
!pip install sentence-transformers
!pip install gensim

Requirement already satisfied: datasets in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.0.0)
Requirement already satisfied: filelock in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (2.4.6)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (3.0.3)
Requirement already satisfied: requests>=2.32.2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (4.68.2)
Requirement already satisfied: xxhash in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (1.19.0)
Requirement already satisfied: packaging in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets) (2026.5.20)
Requirement already satisfied: httpcore==1.* in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: colorama in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sentence-transformers in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (5.12.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.19.0)
Requirement already satisfied: torch>=1.11.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (2.12.0)
Requirement already satisfied: numpy>=1.20.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (2.4.6)
Requirement already satisfied: scikit-learn>=0.22.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (4.68.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: click>=8.4.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: colorama in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from click>=8.4.0->huggingface-hub>=0.23.0->sentence-transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting gensim
  Using cached gensim-4.4.0.tar.gz (23.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.18.5 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from gensim) (2.4.6)
Requirement already satisfied: scipy>=1.7.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from gensim) (1.17.1)
Collecting smart_open>=1.8.1 (from gensim)
  Using cached smart_open-7.6.1-py3-none-any.whl.metadata (25 kB)
Collecting wrapt (from smart_open>=1.8.1->gensim)
  Using cached wrapt-2.2.1-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Using cached smart_open-7.6.1-py3-none-any.whl (64 kB)
Using cached wrapt-2.2.1-cp314-cp314-win_amd64.whl (81 kB)
Building wheels for collected packages: gensim
  Building wheel for gensim (pyproject.toml): started
  Building wheel for gensim (pyproject.toml): finished with status 'error'
Failed to build gensim

  error: subprocess-exited-with-error

  × Building wheel for gensim (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [716 lines of output]
      C:\Users\recla\AppData\Local\Temp\pip-build-env-t9x_127e\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\recla\AppData\Local\Temp\pip-build-env-t9x_127e\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-314\gensim
      copying gensim\downloader.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\interfaces.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\matutils.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\nosy.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\utils.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\__init__.py -> build\lib.win-amd64-cpython-314\gensim
      creating build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\bleicorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\csvcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\dictionary.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\hashdictionary.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\indexedcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\lowcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\malletcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\mmcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\opinosiscorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\sharded_corpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\svmlightcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\textcorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\ucicorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\wikicorpus.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      copying gensim\corpora\__init__.py -> build\lib.win-amd64-cpython-314\gensim\corpora
      creating build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\atmodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\basemodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\bm25model.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\callbacks.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\coherencemodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\doc2vec.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\ensemblelda.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\fasttext.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\hdpmodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\keyedvectors.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\ldamodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\ldamulticore.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\ldaseqmodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\lda_dispatcher.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\lda_worker.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\logentropy_model.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\lsimodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\lsi_dispatcher.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\lsi_worker.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\nmf.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\normmodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\phrases.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\poincare.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\rpmodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\tfidfmodel.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\translation_matrix.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\word2vec.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\_fasttext_bin.py -> build\lib.win-amd64-cpython-314\gensim\models
      copying gensim\models\__init__.py -> build\lib.win-amd64-cpython-314\gensim\models
      creating build\lib.win-amd64-cpython-314\gensim\parsing
      copying gensim\parsing\porter.py -> build\lib.win-amd64-cpython-314\gensim\parsing
      copying gensim\parsing\preprocessing.py -> build\lib.win-amd64-cpython-314\gensim\parsing
      copying gensim\parsing\__init__.py -> build\lib.win-amd64-cpython-314\gensim\parsing
      creating build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\benchmark.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\glove2word2vec.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\make_wiki.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\make_wikicorpus.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\make_wiki_online.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\make_wiki_online_nodebug.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\package_info.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\segment_wiki.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\word2vec2tensor.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\word2vec_standalone.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      copying gensim\scripts\__init__.py -> build\lib.win-amd64-cpython-314\gensim\scripts
      creating build\lib.win-amd64-cpython-314\gensim\similarities
      copying gensim\similarities\annoy.py -> build\lib.win-amd64-cpython-314\gensim\similarities
      copying gensim\similarities\docsim.py -> build\lib.win-amd64-cpython-314\gensim\similarities
      copying gensim\similarities\levenshtein.py -> build\lib.win-amd64-cpython-314\gensim\similarities
      copying gensim\similarities\nmslib.py -> build\lib.win-amd64-cpython-314\gensim\similarities
      copying gensim\similarities\termsim.py -> build\lib.win-amd64-cpython-314\gensim\similarities
      copying gensim\similarities\__init__.py -> build\lib.win-amd64-cpython-314\gensim\similarities
      creating build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\basetmtests.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\simspeed.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\simspeed2.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\svd_error.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_aggregation.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_api.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_atmodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_big.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_bm25model.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_coherencemodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_corpora.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_corpora_dictionary.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_corpora_hashdictionary.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_datatype.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_direct_confirmation.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_doc2vec.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_ensemblelda.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_fasttext.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_glove2word2vec.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_hdpmodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_indirect_confirmation.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_keyedvectors.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_ldamodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_ldaseqmodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_lda_callback.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_lee.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_logentropy_model.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_lsimodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_matutils.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_miislita.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_nmf.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_normmodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_parsing.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_phrases.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_poincare.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_probability_estimation.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_rpmodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_scripts.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_segmentation.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_sharded_corpus.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_similarities.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_similarity_metrics.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_text_analysis.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_tfidfmodel.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_tmdiff.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_translation_matrix.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_utils.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\test_word2vec.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\utils.py -> build\lib.win-amd64-cpython-314\gensim\test
      copying gensim\test\__init__.py -> build\lib.win-amd64-cpython-314\gensim\test
      creating build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\aggregation.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\direct_confirmation_measure.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\indirect_confirmation_measure.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\probability_estimation.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\segmentation.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\text_analysis.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      copying gensim\topic_coherence\__init__.py -> build\lib.win-amd64-cpython-314\gensim\topic_coherence
      running egg_info
      writing gensim.egg-info\PKG-INFO
      writing dependency_links to gensim.egg-info\dependency_links.txt
      writing requirements to gensim.egg-info\requires.txt
      writing top-level names to gensim.egg-info\top_level.txt
      reading manifest file 'gensim.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'COPYING'
      writing manifest file 'gensim.egg-info\SOURCES.txt'
      C:\Users\recla\AppData\Local\Temp\pip-build-env-t9x_127e\overlay\Lib\site-packages\setuptools\command\build_py.py:215: _Warning: Package 'gensim.corpora' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'gensim.corpora' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'gensim.corpora' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'gensim.corpora' to be distributed and are
              already explicitly excluding 'gensim.corpora' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      C:\Users\recla\AppData\Local\Temp\pip-build-env-t9x_127e\overlay\Lib\site-packages\setuptools\command\build_py.py:215: _Warning: Package 'gensim.models' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'gensim.models' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'gensim.models' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'gensim.models' to be distributed and are
              already explicitly excluding 'gensim.models' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      C:\Users\recla\AppData\Local\Temp\pip-build-env-t9x_127e\overlay\Lib\site-packages\setuptools\command\build_py.py:215: _Warning: Package 'gensim.similarities' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'gensim.similarities' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'gensim.similarities' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'gensim.similarities' to be distributed and are
              already explicitly excluding 'gensim.similarities' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data

In [5]:
import pandas as pd
import re
import numpy as np
from collections import Counter

# mdoelo
from sentence_transformers import SentenceTransformer


from sklearn.metrics.pairwise import cosine_similarity

c:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Carga de datasets

Traemos el dataset de sinopsis de peliculas de IMDb desde Hugging Face

In [6]:
df_pelis = pd.read_csv("https://raw.githubusercontent.com/nazarenomm/Sistema-de-recomendacion-de-peliculas/refs/heads/main/data/peliculas_limpio.csv")

Traemos el dataset proporcionado con la información de los usuarios y sus respectivas queries

In [7]:
usuarios = pd.read_csv("https://raw.githubusercontent.com/nazarenomm/Sistema-de-recomendacion-de-peliculas/refs/heads/main/data/usuarios.csv")

Visualizamos las queries

In [8]:
for texto in usuarios['query']:
    print(texto)

Quiero una película donde una mujer enfrenta una amenaza invisible que viene de alguien cercano
Busco algo basado en hechos reales sobre corrupción o poder político
Una comedia donde la relación entre dos personas empieza de forma ridícula o accidental
Algo que haga pensar sobre qué es real y qué es una construcción, con acción pero también ideas
Animación donde el protagonista lucha por su libertad o identidad en un mundo que lo oprime
Un grupo de personas planea un robo o estafa y las cosas se complican de forma inesperada
Una película sobre músicos o artistas que viven al margen, con mucha atmósfera y estilo visual
Acción directa con un héroe que trabaja solo o casi solo contra una organización criminal o corrupta
Algo tranquilo sobre personas que intentan reconectar o entenderse después de una distancia larga
Algo que sea difícil de clasificar, con una lógica narrativa propia, no convencional
No sé bien, algo que valga la pena ver un domingo a la noche, que enganche desde el principio
Quiero algo distinto a lo de siempre, pero tampoco tan raro, con buenas actuaciones supongo
Algo que pueda ver con amigos o solo, que no sea muy larga ni muy corta
No tengo ganas de pensar mucho, pero tampoco quiero algo vacío, algo intermedio

Construimos el dataset de peliculas, agregando un id que faltaba.

In [9]:
df_pelis["id"] = df_pelis.index + 1
df_pelis.head()

,description,keywords,genre,year,name,director,id
0,"Orin Boyd, un duro policía de una comisaría de...","vietnam war veteran, heroína, drogas, narcotra...","acción, crimen, suspense",2001.0,Herida abierta,Andrzej Bartkowiak,1
1,Al llegar a un pequeño pueblo donde ha heredad...,"herencia, hostess, comedia negra, pueblo, magia","comedia, terror",1989.0,"Elvira, reina de las tinieblas",James Signorelli,2
2,Una mujer finge su muerte en un intento de esc...,"violencia doméstica, muerte fingida, borderlin...","drama, suspense",1991.0,Durmiendo con su enemigo,Joseph Ruben,3
3,Durante un memorial en la ciudad natal de su p...,"manic pixie dream girl, publicidad, bad public...","comedia, drama, romance",2005.0,Elizabethtown,Cameron Crowe,4
4,Las pruebas nucleares francesas irradian a una...,"monstruo gigante, iguana, militar, giant footp...","acción, ciencia ficción, suspense",1998.0,Godzilla,Roland Emmerich,5

## Preprocesado

### Función de limpieza de texto

Aplicamos un pipeline de limpieza estándar: minúsculas, eliminación de puntuación y palabras con números.

In [10]:
def limpiar_texto(text):
    if not isinstance(text, str):
        return ''
    text = re.sub(r'<[^>]+>', ' ', text)        # remover HTML si hubiera
    text = re.sub(r'[^\w\s\.,;:!?áéíóúüñ-]', ' ', text)  # caracteres extraños
    text = re.sub(r'\s+', ' ', text)             # espacios múltiples
    return text.strip()

Unificamos las variables relevantes en un texto (todas menos año)

In [11]:
df_pelis["texto"] = (
    df_pelis["name"].apply(limpiar_texto) + ". "
    + df_pelis["description"].apply(limpiar_texto) + " "
    + df_pelis["director"].fillna('').apply(limpiar_texto) + ". " # probar agregar queries como "quiero ver una de Tarantino" a ver si funciona, sino sacar
    + df_pelis["year"].apply(lambda x: str(int(x)) if pd.notnull(x) else '') + ". "
    + df_pelis["genre"].apply(limpiar_texto) + ". "
    + df_pelis["keywords"].apply(limpiar_texto)
)

In [12]:
df_pelis.texto.iloc[0]

'Herida abierta. Orin Boyd, un duro policía de una comisaría del centro de la ciudad, descubre una red de policías corruptos. Andrzej Bartkowiak. 2001. acción, crimen, suspense. vietnam war veteran, heroína, drogas, narcotraficante, corrupt cop'

#### El espanglish en ``genre`` y ``keywords``:  
El modelo multilingüe maneja texto en múltiples idiomas, pero fue entrenado con documentos monolingües por separado, no necesariamente con mezcla de idiomas dentro del mismo string

¿Es un problema grave? No. El modelo multilingüe es bastante robusto a esto. Pero sí es algo valioso para mencionar como limitación del corpus.

## Embedding de peliculas

In [13]:
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2962.82it/s]

### Calcular embedding de cada película

No hace falta hacer el promedio para calcularlo, el output del modelo ya es el embedding del documento (pelicula).

In [14]:
pelis_embeddings = model.encode(df_pelis['texto'].tolist(), show_progress_bar=True)

Batches: 100%|██████████| 156/156 [02:30<00:00,  1.04it/s]

Como el dataset de películas y el de embeddings se construyeron en el mismo orden,podemos unirlos directamente por índice

In [15]:
df_pelis = df_pelis.reset_index(drop=True)

pelis_embeddings_df = pd.DataFrame(pelis_embeddings)
pelis_embeddings_df = pelis_embeddings_df.merge(
    df_pelis[['id', 'name']], 
    left_index=True, 
    right_index=True
)

In [16]:
pelis_embeddings_df.head()

,0,1,2,3,4,5,6,7,8,9,...,376,377,378,379,380,381,382,383,id,name
0,-0.031083,0.032719,-0.272750,0.105669,0.088466,0.341037,0.109469,0.170736,0.048047,-0.134747,...,-0.053232,0.032655,-0.199530,-0.102709,0.034748,-0.105462,0.243188,0.014966,1,Herida abierta
1,-0.007789,0.076888,-0.077062,0.274105,-0.079885,-0.025508,0.314847,0.059361,0.081432,0.050591,...,0.168026,0.220522,-0.022279,-0.104578,0.325791,-0.082222,-0.040965,-0.080095,2,"Elvira, reina de las tinieblas"
2,-0.017430,0.006371,-0.100607,0.260501,0.053605,0.227207,0.040888,-0.065317,0.184578,-0.041667,...,0.132501,0.318629,-0.022673,0.075589,0.229808,0.034454,0.114800,-0.044366,3,Durmiendo con su enemigo
3,0.137272,0.015918,0.013975,0.060339,-0.133089,0.079739,0.129728,-0.093552,0.063227,0.041110,...,-0.029802,0.355402,0.058575,-0.094542,0.238030,0.101194,0.021751,-0.007258,4,Elizabethtown
4,-0.165777,0.050897,-0.000996,-0.207756,0.106295,-0.271873,-0.016602,0.089710,0.047141,0.133440,...,-0.091462,-0.023140,-0.099317,0.237066,0.205077,-0.302631,0.368318,0.098505,5,Godzilla

## Embeddings de usuarios

Aplicamos la misma función de limpieza que usamos para las sinopsis. La verdad que no hace falta pero debería ser parte del pipeline operativo habitual.

In [17]:
# data_clean_users = pd.DataFrame(usuarios["query"].apply(limpiar_texto))

### Sin promediar

Con ``sentence_transformer`` no hace falta calcular los promedios de la query y el historial, se puede pasar todo el texto de una.

La desventaja es que no podemos controlar la importancia que se le da al historial

el modelo tiene limite de 512 tokens, podemos chequear antes de calcular los embeddings.

In [18]:
# contar cantidad de palabras en df["texto"]
df_pelis["word_count"] = df_pelis["texto"].apply(lambda x: len(str(x).split()))
print("Cantidad maxima de palabras:")
print(df_pelis["word_count"].max())
print("Mediana de palabras:")
print(df_pelis["word_count"].median())

Cantidad maxima de palabras:
79
Mediana de palabras:
45.0

In [19]:
usuarios["query_word_count"] = usuarios["query"].apply(lambda x: len(str(x).split()))
print("Cantidad maxima de palabras en queries de usuarios:")
print(usuarios["query_word_count"].max())
print("Mediana de palabras en queries de usuarios:")
print(usuarios["query_word_count"].median())

Cantidad maxima de palabras en queries de usuarios:
19
Mediana de palabras en queries de usuarios:
15.5

Igualmente hay que considerar que las queries son cortas, podrían haber más largas en un futuro (quizás plantear una longitud máxima)

En promedio una palabra española se tokeniza en 1.5-2 tokens. Entonces:

``44 palabras × 5 películas + query (max 30 palabras, por ejemplo) ≈ 250 palabras ≈ 375-500 tokens``

Ejemplo exagerado del tokenizador

In [20]:
tokenizer = model.tokenizer

texto = "narcotraficante corruptísimo anticonstitucional"
tokens = tokenizer.tokenize(texto)
print(tokens)
print(f"palabras: 3 → tokens: {len(tokens)}")

['▁na', 'rc', 'otra', 'fica', 'nte', '▁', 'corrupt', 'ísimo', '▁antico', 'n', 'stitu', 'cional']
palabras: 3 → tokens: 12

In [21]:
def build_user_text(row, df_pelis):
    # Query del usuario
    partes = [row['query']]
    
    # Descripciones de las 5 películas del historial
    for col in ['pelicula_1','pelicula_2','pelicula_3','pelicula_4','pelicula_5']:
        nombre = row[col]
        match = df_pelis[df_pelis['name'] == nombre]['texto']
        if len(match):
            partes.append(match.values[0])
    
    return ' '.join(partes)

user_texts = usuarios.apply(lambda r: build_user_text(r, df_pelis), axis=1).tolist()

In [22]:
user_embeddings = model.encode(user_texts, show_progress_bar=True)

Batches: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s]

In [23]:
user_embeddings_df = pd.DataFrame(user_embeddings)
user_embeddings_df = user_embeddings_df.merge(usuarios[['id']], left_index=True, right_index=True)
user_embeddings_df.head()

,0,1,2,3,4,5,6,7,8,9,...,375,376,377,378,379,380,381,382,383,id
0,-0.238107,-0.128500,-0.207465,0.260500,0.247655,0.290276,0.095238,-0.093639,0.200505,0.013914,...,0.297109,0.074182,0.340460,-0.116549,0.221071,0.159515,-0.142231,0.079386,-0.026740,U01
1,-0.249083,0.191250,-0.289829,0.216814,0.266727,0.115557,0.088643,-0.020128,0.025625,0.020821,...,-0.078047,-0.033263,0.171906,-0.238212,-0.107696,0.169403,-0.052990,-0.165263,-0.162586,U02
2,-0.010083,-0.286078,-0.028388,-0.073591,0.070636,0.379458,0.180789,0.056127,0.217427,-0.043305,...,0.053136,0.069376,0.004023,-0.328375,-0.023175,0.125202,0.085754,0.105665,0.007408,U03
3,-0.135121,-0.022123,-0.174233,-0.013320,0.024583,-0.171468,0.109334,0.055659,0.042445,0.104168,...,-0.050089,-0.095498,0.186531,-0.198212,0.121175,0.162361,0.030514,-0.036455,0.011859,U04
4,-0.022891,0.008990,-0.241990,0.069403,0.142337,0.157824,0.238181,-0.189650,0.251596,0.146036,...,0.137518,0.138678,0.324707,0.010308,0.202955,0.194683,-0.085762,-0.002339,-0.013053,U05

### Promediando

In [24]:
queries_embeddings = model.encode(usuarios['query'].tolist(), show_progress_bar=True)

Batches: 100%|██████████| 1/1 [00:00<00:00,  7.23it/s]

In [25]:
def get_all_historial_embeddings(usuarios_df, pelis_embeddings_df):
    all_embeddings = []
    
    for _, usuario_row in usuarios_df.iterrows():
        historial_embeddings = []
        
        for col in ['pelicula_1','pelicula_2','pelicula_3','pelicula_4','pelicula_5']:
            nombre = usuario_row[col]
            peli_emb = pelis_embeddings_df[pelis_embeddings_df['name'] == nombre]
            if not peli_emb.empty:
                historial_embeddings.append(peli_emb.drop(columns=['id', 'name']).values[0])
            else:
                print(f"Película '{nombre}' no encontrada.")
        
        embedding_promedio = np.mean(historial_embeddings, axis=0)
        all_embeddings.append(embedding_promedio)
    
    return np.array(all_embeddings)

historial_embeddings = get_all_historial_embeddings(usuarios, pelis_embeddings_df)

Película 'Rec' no encontrada.
Película 'El secreto de sus ojos' no encontrada.
Película 'El exorcista' no encontrada.
Película 'Intocable' no encontrada.
Película 'Una mente brillante' no encontrada.
Película 'Paddington' no encontrada.

### Configuración de Ollama

Iniciamos el servidor de Ollama en background y descargamos el modelo a usar.

In [26]:
!pip install ollama

Requirement already satisfied: ollama in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.6.2)
Requirement already satisfied: httpx>=0.27 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ollama) (2.13.4)
Requirement already satisfied: anyio in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx>=0.27->ollama) (4.13.0)
Requirement already satisfied: certifi in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx>=0.27->ollama) (2026.5.20)
Requirement already satisfied: httpcore==1.* in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx>=0.27->ollama) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic>=2.9->ollama) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic>=2.9->ollama) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\recla\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic>=2.9->ollama) (0.4.2)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
import subprocess, time, ollama

# Iniciar servidor Ollama en background
try:
    subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(3)  # esperar que levante
    print("server ollama iniciado")
except FileNotFoundError:
    print("Servidor de ollama no encontrado")
# Descargar modelo (solo la primera vez)
try:
    ollama.pull('llama3.2')
except Exception as e:
    print(f"Error la descargar el modelo: {e}")

server ollama iniciado

### Reescritura de query e inferencia de pesos con LLM (llamada unificada)

Usamos el LLM para hacer dos cosas en **una sola llamada**:

1. **`query_expandida`**: reescribir la query coloquial del usuario como una descripción corta estilo sinopsis cinematográfica, incluyendo género, mood y keywords. Esto reduce la brecha semántica con los textos del dataset (que combinan sinopsis + género + keywords).

2. **`weights`** y **`direccion`**: inferir cuánto peso darle a la query vs. el historial, y si buscar películas similares al perfil o distintas.

**¿Por qué la reescritura mejora los resultados?** El espacio vectorial fue construido con textos que incluyen género y keywords del dataset. Una query coloquial queda lejos de ese espacio; una reescritura con vocabulario cinematográfico queda cerca.

In [46]:
import json as json_lib

def procesar_query_con_llm(query: str) -> dict:
    """
    Una sola llamada al LLM que devuelve:
      - query_expandida: sinopsis corta estilo dataset (sinopsis + género + keywords)
      - weights: [w_query, w_historial] sumando 1.0
      - direccion: 'similar' o 'distinto'
    """
    prompt = f"""You are a movie recommendation system. Analyze the following user search request and return a JSON with three fields.

User search: "{query}"

Fields to return:

1. "query_expandida": Rewrite the user request as a SHORT cinematic description (2 sentences maximum) IN SPANISH.
   - Use the same style as movie synopses: describe the plot, mood, or main character situation.
   - Explicitly include relevant genres (e.g.: suspense, drama, comedia, acción, terror, crimen, romance, ciencia ficción, animación, biografía).
   - Include thematic keywords (e.g.: corrupción, robo, amor, identidad, persecución, amistad).
   - Do NOT mention any specific movie titles.

2. "weights": a list [query_weight, history_weight] that must sum to exactly 1.0.
   - Increase query_weight when the user is specific about what they want (mentions genre, theme, mood, director).
   - Increase history_weight when the request is vague or generic (e.g. "something good", "I don't know what to watch").

3. "direccion": either "similar" or "distinto".
   - "similar": user wants more of the same (same genre, same style as their history).
   - "distinto": user wants to step outside their comfort zone or try something different from usual.

Respond ONLY with valid JSON, no extra text:
{{
  "query_expandida": "...",
  "weights": [query_weight, history_weight],
  "direccion": "similar" or "distinto"
}}"""

    response = ollama.chat(
        model='llama3.2',
        messages=[{'role': 'user', 'content': prompt}],
        format='json',
        options={'temperature': 0.3, 'seed': 42}
    )

    raw = response.message.content.strip()

    try:
        parsed = json_lib.loads(raw)
        weights = parsed.get('weights', [0.7, 0.3])
        direccion_raw = parsed.get('direccion', 'similar').lower().strip()
        if direccion_raw in ('similar', 'parecido', 'mismo'):
            direccion = 'similar'
        elif direccion_raw in ('distinto', 'different', 'distinct', 'diferente', 'otro'):
            direccion = 'distinto'
        else:
            direccion = 'similar'
        query_expandida = parsed.get('query_expandida', query)
        assert len(weights) == 2, "weights must have 2 elements"
        assert abs(sum(weights) - 1.0) < 0.05, f"weights must sum to ~1, got {sum(weights)}"
        return {'query_expandida': query_expandida, 'weights': weights, 'direccion': direccion}
    except Exception as e:
        print(f"[WARN] JSON parse error for query '{query[:40]}...': {e}")
        return {'query_expandida': query, 'weights': [0.7, 0.3], 'direccion': 'similar'}


# Procesar todas las queries
resultados_llm = []
for query in usuarios['query']:
    res = procesar_query_con_llm(query)
    resultados_llm.append(res)
    print(f"Original:   {query}")
    print(f"Expandida:  {res['query_expandida']}")
    print(f"Weights:    {res['weights']} | Dirección: {res['direccion']}")
    print()

usuarios['query_reescrita'] = [r['query_expandida'] for r in resultados_llm]
parametros_usuarios = [{'weights': r['weights'], 'direccion': r['direccion']} for r in resultados_llm]

Original:   Quiero una película donde una mujer enfrenta una amenaza invisible que viene de alguien cercano
Expandida:  Una mujer se enfrenta a una amenaza invisible que proviene de alguien cercano en un thriller psicológico con elementos de suspense y drama.
Weights:    [0.8, 0.2] | Dirección: similar

Original:   Busco algo basado en hechos reales sobre corrupción o poder político
Expandida:  Una película que explora la oscura realidad de la corrupción política, donde el poder y el dinero se entrelazan en un juego peligroso. Un thriller intenso que te mantendrá en vilo.
Weights:    [0.8, 0.2] | Dirección: similar

Original:   Una comedia donde la relación entre dos personas empieza de forma ridícula o accidental
Expandida:  Una comedia que explora la relación entre dos personas de manera inesperada y divertida, con un tono ligero y una mezcla de situaciones absurdas y emocionales. La historia puede girar en torno a temas como la amistad, el amor o la identidad.
Weights:    [0.8, 0.2] | Dirección: similar

Original:   Algo que haga pensar sobre qué es real y qué es una construcción, con acción pero también ideas
Expandida:  Una película que explora la frontera entre lo real y lo constructo, con una trama emocionante pero también profundas reflexiones sobre la identidad y la realidad. Géneros: ciencia ficción, drama, acción.
Weights:    [0.7, 0.3] | Dirección: distinto

Original:   Animación donde el protagonista lucha por su libertad o identidad en un mundo que lo oprime
Expandida:  En un mundo opresivo, un joven lucha por su libertad y identidad en una historia de animación que combina elementos de drama y suspense.
Weights:    [0.8, 0.2] | Dirección: distinto

Original:   Un grupo de personas planea un robo o estafa y las cosas se complican de forma inesperada
Expandida:  Un grupo de personas planean un robo o estafa que se complican de forma inesperada, con giros y vueltas sorprendentes. La tensión y la incertidumbre crecen en una historia emocionante.
Weights:    [0.8, 0.2] | Dirección: similar

Original:   Una película sobre músicos o artistas que viven al margen, con mucha atmósfera y estilo visual
Expandida:  Una película sobre músicos o artistas que viven al margen, llena de atmósfera y estilo visual, con un toque de drama y crimen.
Weights:    [0.7, 0.3] | Dirección: similar

Original:   Acción directa con un héroe que trabaja solo o casi solo contra una organización criminal o corrupta
Expandida:  Un héroe solitario lucha contra una organización criminal corrupta en un thriller de acción que explora temas de corrupción y justicia.
Weights:    [0.8, 0.2] | Dirección: similar

Original:   Algo tranquilo sobre personas que intentan reconectar o entenderse después de una distancia larga
Expandida:  Una historia de amor y redescubrimiento que explora la complejidad de las relaciones después de una gran distancia. Un drama romántico con un tono introspectivo y emocional.
Weights:    [0.7, 0.3] | Dirección: similar

Original:   Algo que sea difícil de clasificar, con una lógica narrativa propia, no convencional
Expandida:  Una película que combina elementos de suspense y ciencia ficción con una narrativa única y no convencional. La trama sigue a un personaje que se enfrenta a una realidad alternativa donde la lógica y el tiempo están en juego.
Weights:    [0.6, 0.4] | Dirección: distinto

Original:   No sé bien, algo que valga la pena ver un domingo a la noche, que enganche desde el principio
Expandida:  Una película de suspense que sigue a un personaje que se ve envuelto en una conspiración criminal. La trama es emocionante y el ritmo acelerado mantiene al espectador enganchado desde el principio.
Weights:    [0.7, 0.3] | Dirección: similar

Original:   Quiero algo distinto a lo de siempre, pero tampoco tan raro, con buenas actuaciones supongo
Expandida:  Busco una película con actuaciones destacadas que combine elementos de drama y suspense, posiblemente con un enfoque en la corrupción o el crimen, pero sin ser demasiado extrema.
Weights:    [0.7, 0.3] | Dirección: distinto

Original:   Algo que pueda ver con amigos o solo, que no sea muy larga ni muy corta
Expandida:  Una película de acción y comedia que sigue la historia de un grupo de amigos mientras se ven envueltos en una serie de aventuras y desafíos, con un tono ligero y divertido. La película explora temas como amistad y lealtad.
Weights:    [0.8, 0.2] | Dirección: similar

Original:   No tengo ganas de pensar mucho, pero tampoco quiero algo vacío, algo intermedio
Expandida:  Una película que combina elementos de drama y comedia para explorar la vida cotidiana de una persona que busca equilibrio entre la rutina y la libertad. Un género como el drama o la comedia podría ser adecuado.
Weights:    [0.4, 0.6] | Dirección: similar

In [47]:
# Embeddings de las queries REESCRITAS (mejor alineadas con el espacio de sinopsis)
queries_reescritas_embeddings = model.encode(usuarios['query_reescrita'].tolist(), show_progress_bar=True)

# Construir embedding por usuario con pesos dinámicos
user_embeddings_dinamico = []

for i, params in enumerate(parametros_usuarios):
    w = params['weights']
    emb = np.average(
        [queries_reescritas_embeddings[i], historial_embeddings[i]],
        axis=0,
        weights=w
    )
    user_embeddings_dinamico.append(emb)

user_embeddings_dinamico = np.array(user_embeddings_dinamico)

Batches: 100%|██████████| 1/1 [00:00<00:00,  2.47it/s]

## Recomendaciones

### Dinámico (LLM)

In [48]:
scores_dinamico = cosine_similarity(user_embeddings_dinamico, pelis_embeddings)
# TODO: filtrar películas ya vistas en el historial

# Top-5 con dirección dinámica por usuario
top5_indices_dinamico = []
for i, params in enumerate(parametros_usuarios):
    if params['direccion'] == 'distinto':
        indices = scores_dinamico[i].argsort()[:5]          # bottom-5: más lejanas
    else:
        indices = scores_dinamico[i].argsort()[-5:][::-1]   # top-5: más cercanas
    top5_indices_dinamico.append(indices)

# Ver resultados
for i, row in usuarios.iterrows():
    params = parametros_usuarios[i]
    print(f"\n{row['nombre']} ({row['tipo_perfil']})")
    print(f"Query:      {row['query']}")
    print(f"Reescrita:  {row['query_reescrita']}")
    print(f"Pesos:      query={params['weights'][0]}, historial={params['weights'][1]}")
    print(f"Dirección:  {params['direccion']}")
    for idx in top5_indices_dinamico[i]:
        pelicula = df_pelis.iloc[idx]
        score = scores_dinamico[i, idx]
        print(f"  {pelicula['name']} ({int(pelicula['year']) if not pd.isna(pelicula['year']) else 'N/A'}) — {score:.4f}")

Valentina (definido)
Query:      Quiero una película donde una mujer enfrenta una amenaza invisible que viene de alguien cercano
Reescrita:  Una mujer se enfrenta a una amenaza invisible que proviene de alguien cercano en un thriller psicológico con elementos de suspense y drama.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  El ente (1983) — 0.7165
  Inland Empire (2007) — 0.7142
  Insectos (2007) — 0.6691
  Morir todavía (1992) — 0.6641
  Nunca hables con extraños (1996) — 0.6637

Rodrigo (definido)
Query:      Busco algo basado en hechos reales sobre corrupción o poder político
Reescrita:  Una película que explora la oscura realidad de la corrupción política, donde el poder y el dinero se entrelazan en un juego peligroso. Un thriller intenso que te mantendrá en vilo.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Hidden (Lo oculto) (1989) — 0.7059
  Cliente muerto no paga (1982) — 0.6591
  Alone in the Dark (2006) — 0.6584
  Gritos de muerte (2004) — 0.6450
  El jardinero fiel (2005) — 0.6397

Camila (definido)
Query:      Una comedia donde la relación entre dos personas empieza de forma ridícula o accidental
Reescrita:  Una comedia que explora la relación entre dos personas de manera inesperada y divertida, con un tono ligero y una mezcla de situaciones absurdas y emocionales. La historia puede girar en torno a temas como la amistad, el amor o la identidad.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Happiness (1998) — 0.6861
  Escuela de novatos (2004) — 0.6812
  Date Movie (2006) — 0.6741
  Amor loco (1995) — 0.6677
  Embriagado de amor (2003) — 0.6623

Tomás (definido)
Query:      Algo que haga pensar sobre qué es real y qué es una construcción, con acción pero también ideas
Reescrita:  Una película que explora la frontera entre lo real y lo constructo, con una trama emocionante pero también profundas reflexiones sobre la identidad y la realidad. Géneros: ciencia ficción, drama, acción.
Pesos:      query=0.7, historial=0.3
Dirección:  distinto
  Johnny Superstar (1988) — 0.0024
  Hum Saath-Saath Hain (1999) — 0.0285
  Camino a la gloria (2006) — 0.0363
  Abajo el periscopio (1996) — 0.0395
  Batalla en Seattle (2008) — 0.0444

Lucía (definido)
Query:      Animación donde el protagonista lucha por su libertad o identidad en un mundo que lo oprime
Reescrita:  En un mundo opresivo, un joven lucha por su libertad y identidad en una historia de animación que combina elementos de drama y suspense.
Pesos:      query=0.8, historial=0.2
Dirección:  distinto
  Timber Falls (2008) — -0.0515
  American Pie: ¡Menuda boda! (2003) — -0.0363
  Rock Star (2001) — 0.0055
  Abajo el periscopio (1996) — 0.0315
  The Beatles Anthology (1995) — 0.0359

Martín (definido)
Query:      Un grupo de personas planea un robo o estafa y las cosas se complican de forma inesperada
Reescrita:  Un grupo de personas planean un robo o estafa que se complican de forma inesperada, con giros y vueltas sorprendentes. La tensión y la incertidumbre crecen en una historia emocionante.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Proyecto Brainstorm (1983) — 0.6197
  Plan oculto (2006) — 0.6147
  Máximo riesgo (1993) — 0.5984
  Out of sight (Un romance muy peligroso) (1998) — 0.5960
  Hidden (Lo oculto) (1989) — 0.5863

Sofía (definido)
Query:      Una película sobre músicos o artistas que viven al margen, con mucha atmósfera y estilo visual
Reescrita:  Una película sobre músicos o artistas que viven al margen, llena de atmósfera y estilo visual, con un toque de drama y crimen.
Pesos:      query=0.7, historial=0.3
Dirección:  similar
  Conociendo a Julia (2004) — 0.6770
  El vagón de la muerte (2008) — 0.6614
  Peligrosamente juntos (1986) — 0.6449
  Aquarius (1987) — 0.6439
  Sangre por sangre (1993) — 0.6414

Diego (definido)
Query:      Acción directa con un héroe que trabaja solo o casi solo contra una organización criminal o corrupta
Reescrita:  Un héroe solitario lucha contra una organización criminal corrupta en un thriller de acción que explora temas de corrupción y justicia.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  El coche fantástico (N/A) — 0.6913
  Snake Eyes (Ojos de serpiente) (1998) — 0.6780
  Daredevil (2003) — 0.6755
  Open Range (2003) — 0.6598
  El poder del talismán (2003) — 0.6551

Elena (definido)
Query:      Algo tranquilo sobre personas que intentan reconectar o entenderse después de una distancia larga
Reescrita:  Una historia de amor y redescubrimiento que explora la complejidad de las relaciones después de una gran distancia. Un drama romántico con un tono introspectivo y emocional.
Pesos:      query=0.7, historial=0.3
Dirección:  similar
  El juego del amor (2007) — 0.7259
  It's All About Love (Todo es por amor) (2003) — 0.7008
  Timecode (2000) — 0.6864
  El sueño de una noche de verano, de William Shakespeare (1999) — 0.6861
  El diario de Noa (2004) — 0.6823

Facundo (definido)
Query:      Algo que sea difícil de clasificar, con una lógica narrativa propia, no convencional
Reescrita:  Una película que combina elementos de suspense y ciencia ficción con una narrativa única y no convencional. La trama sigue a un personaje que se enfrenta a una realidad alternativa donde la lógica y el tiempo están en juego.
Pesos:      query=0.6, historial=0.4
Dirección:  distinto
  Johnny Superstar (1988) — -0.0338
  Hum Saath-Saath Hain (1999) — 0.0433
  Tierra (2007) — 0.0550
  Days of Glory (2007) — 0.0620
  Top Chef (2006) — 0.0647

Julián (ambiguo)
Query:      No sé bien, algo que valga la pena ver un domingo a la noche, que enganche desde el principio
Reescrita:  Una película de suspense que sigue a un personaje que se ve envuelto en una conspiración criminal. La trama es emocionante y el ritmo acelerado mantiene al espectador enganchado desde el principio.
Pesos:      query=0.7, historial=0.3
Dirección:  similar
  Hidden (Lo oculto) (1989) — 0.7081
  Bowfinger, el pícaro (1999) — 0.6818
  Alone in the Dark (2006) — 0.6771
  Snake Eyes (Ojos de serpiente) (1998) — 0.6726
  Inland Empire (2007) — 0.6594

Mariana (ambiguo)
Query:      Quiero algo distinto a lo de siempre, pero tampoco tan raro, con buenas actuaciones supongo
Reescrita:  Busco una película con actuaciones destacadas que combine elementos de drama y suspense, posiblemente con un enfoque en la corrupción o el crimen, pero sin ser demasiado extrema.
Pesos:      query=0.7, historial=0.3
Dirección:  distinto
  Camino a la gloria (2006) — -0.0685
  Windtalkers (2002) — -0.0630
  Un entrenador de primera (1996) — -0.0570
  Papá por sorpresa (2008) — -0.0519
  Frasier (1993) — -0.0509

Nicolás (ambiguo)
Query:      Algo que pueda ver con amigos o solo, que no sea muy larga ni muy corta
Reescrita:  Una película de acción y comedia que sigue la historia de un grupo de amigos mientras se ven envueltos en una serie de aventuras y desafíos, con un tono ligero y divertido. La película explora temas como amistad y lealtad.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Qué les pasa a los hombres (2009) — 0.6351
  Pensamientos mortales (1991) — 0.6328
  Happiness (1998) — 0.6051
  Conociendo a Julia (2004) — 0.6014
  Aquellos maravillosos 70 (2003) — 0.5965

Paula (ambiguo)
Query:      No tengo ganas de pensar mucho, pero tampoco quiero algo vacío, algo intermedio
Reescrita:  Una película que combina elementos de drama y comedia para explorar la vida cotidiana de una persona que busca equilibrio entre la rutina y la libertad. Un género como el drama o la comedia podría ser adecuado.
Pesos:      query=0.4, historial=0.6
Dirección:  similar
  Conociendo a Julia (2004) — 0.7074
  Bowfinger, el pícaro (1999) — 0.7015
  Lost in Translation (2004) — 0.6998
  Tránsito (2006) — 0.6993
  Qué les pasa a los hombres (2009) — 0.6970

In [49]:
scores_dinamico = cosine_similarity(user_embeddings_dinamico, pelis_embeddings)

def get_historial_indices(usuario_row, df_pelis):
    """Devuelve el set de índices de las películas ya vistas por el usuario."""
    indices = set()
    for col in ['pelicula_1', 'pelicula_2', 'pelicula_3', 'pelicula_4', 'pelicula_5']:
        nombre = usuario_row[col]
        match = df_pelis[df_pelis['name'] == nombre].index
        indices.update(match.tolist())
    return indices

# Top-5 con dirección dinámica y sin películas del historial
top5_indices_dinamico = []
for i, (params, (_, row)) in enumerate(zip(parametros_usuarios, usuarios.iterrows())):
    historial_idx = list(get_historial_indices(row, df_pelis))
    scores_i = scores_dinamico[i].copy()

    if params['direccion'] == 'distinto':
        scores_i[historial_idx] = np.inf   # excluir del bottom-5
        indices = scores_i.argsort()[:5]
    else:
        scores_i[historial_idx] = -np.inf  # excluir del top-5
        indices = scores_i.argsort()[-5:][::-1]

    top5_indices_dinamico.append(indices)

# Ver resultados
for i, row in usuarios.iterrows():
    params = parametros_usuarios[i]
    print(f"\n{row['nombre']} ({row['tipo_perfil']})")
    print(f"Query:      {row['query']}")
    print(f"Reescrita:  {row['query_reescrita']}")
    print(f"Pesos:      query={params['weights'][0]}, historial={params['weights'][1]}")
    print(f"Dirección:  {params['direccion']}")
    for idx in top5_indices_dinamico[i]:
        pelicula = df_pelis.iloc[idx]
        score = scores_dinamico[i, idx]
        print(f"  {pelicula['name']} ({int(pelicula['year']) if not pd.isna(pelicula['year']) else 'N/A'}) — {score:.4f}")

Valentina (definido)
Query:      Quiero una película donde una mujer enfrenta una amenaza invisible que viene de alguien cercano
Reescrita:  Una mujer se enfrenta a una amenaza invisible que proviene de alguien cercano en un thriller psicológico con elementos de suspense y drama.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  El ente (1983) — 0.7165
  Inland Empire (2007) — 0.7142
  Insectos (2007) — 0.6691
  Morir todavía (1992) — 0.6641
  Nunca hables con extraños (1996) — 0.6637

Rodrigo (definido)
Query:      Busco algo basado en hechos reales sobre corrupción o poder político
Reescrita:  Una película que explora la oscura realidad de la corrupción política, donde el poder y el dinero se entrelazan en un juego peligroso. Un thriller intenso que te mantendrá en vilo.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Hidden (Lo oculto) (1989) — 0.7059
  Cliente muerto no paga (1982) — 0.6591
  Alone in the Dark (2006) — 0.6584
  Gritos de muerte (2004) — 0.6450
  El jardinero fiel (2005) — 0.6397

Camila (definido)
Query:      Una comedia donde la relación entre dos personas empieza de forma ridícula o accidental
Reescrita:  Una comedia que explora la relación entre dos personas de manera inesperada y divertida, con un tono ligero y una mezcla de situaciones absurdas y emocionales. La historia puede girar en torno a temas como la amistad, el amor o la identidad.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Happiness (1998) — 0.6861
  Escuela de novatos (2004) — 0.6812
  Date Movie (2006) — 0.6741
  Amor loco (1995) — 0.6677
  Embriagado de amor (2003) — 0.6623

Tomás (definido)
Query:      Algo que haga pensar sobre qué es real y qué es una construcción, con acción pero también ideas
Reescrita:  Una película que explora la frontera entre lo real y lo constructo, con una trama emocionante pero también profundas reflexiones sobre la identidad y la realidad. Géneros: ciencia ficción, drama, acción.
Pesos:      query=0.7, historial=0.3
Dirección:  distinto
  Johnny Superstar (1988) — 0.0024
  Hum Saath-Saath Hain (1999) — 0.0285
  Camino a la gloria (2006) — 0.0363
  Abajo el periscopio (1996) — 0.0395
  Batalla en Seattle (2008) — 0.0444

Lucía (definido)
Query:      Animación donde el protagonista lucha por su libertad o identidad en un mundo que lo oprime
Reescrita:  En un mundo opresivo, un joven lucha por su libertad y identidad en una historia de animación que combina elementos de drama y suspense.
Pesos:      query=0.8, historial=0.2
Dirección:  distinto
  Timber Falls (2008) — -0.0515
  American Pie: ¡Menuda boda! (2003) — -0.0363
  Rock Star (2001) — 0.0055
  Abajo el periscopio (1996) — 0.0315
  The Beatles Anthology (1995) — 0.0359

Martín (definido)
Query:      Un grupo de personas planea un robo o estafa y las cosas se complican de forma inesperada
Reescrita:  Un grupo de personas planean un robo o estafa que se complican de forma inesperada, con giros y vueltas sorprendentes. La tensión y la incertidumbre crecen en una historia emocionante.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Proyecto Brainstorm (1983) — 0.6197
  Plan oculto (2006) — 0.6147
  Máximo riesgo (1993) — 0.5984
  Out of sight (Un romance muy peligroso) (1998) — 0.5960
  Hidden (Lo oculto) (1989) — 0.5863

Sofía (definido)
Query:      Una película sobre músicos o artistas que viven al margen, con mucha atmósfera y estilo visual
Reescrita:  Una película sobre músicos o artistas que viven al margen, llena de atmósfera y estilo visual, con un toque de drama y crimen.
Pesos:      query=0.7, historial=0.3
Dirección:  similar
  Conociendo a Julia (2004) — 0.6770
  El vagón de la muerte (2008) — 0.6614
  Peligrosamente juntos (1986) — 0.6449
  Aquarius (1987) — 0.6439
  Sangre por sangre (1993) — 0.6414

Diego (definido)
Query:      Acción directa con un héroe que trabaja solo o casi solo contra una organización criminal o corrupta
Reescrita:  Un héroe solitario lucha contra una organización criminal corrupta en un thriller de acción que explora temas de corrupción y justicia.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  El coche fantástico (N/A) — 0.6913
  Snake Eyes (Ojos de serpiente) (1998) — 0.6780
  Daredevil (2003) — 0.6755
  Open Range (2003) — 0.6598
  El poder del talismán (2003) — 0.6551

Elena (definido)
Query:      Algo tranquilo sobre personas que intentan reconectar o entenderse después de una distancia larga
Reescrita:  Una historia de amor y redescubrimiento que explora la complejidad de las relaciones después de una gran distancia. Un drama romántico con un tono introspectivo y emocional.
Pesos:      query=0.7, historial=0.3
Dirección:  similar
  El juego del amor (2007) — 0.7259
  It's All About Love (Todo es por amor) (2003) — 0.7008
  Timecode (2000) — 0.6864
  El sueño de una noche de verano, de William Shakespeare (1999) — 0.6861
  El diario de Noa (2004) — 0.6823

Facundo (definido)
Query:      Algo que sea difícil de clasificar, con una lógica narrativa propia, no convencional
Reescrita:  Una película que combina elementos de suspense y ciencia ficción con una narrativa única y no convencional. La trama sigue a un personaje que se enfrenta a una realidad alternativa donde la lógica y el tiempo están en juego.
Pesos:      query=0.6, historial=0.4
Dirección:  distinto
  Johnny Superstar (1988) — -0.0338
  Hum Saath-Saath Hain (1999) — 0.0433
  Tierra (2007) — 0.0550
  Days of Glory (2007) — 0.0620
  Top Chef (2006) — 0.0647

Julián (ambiguo)
Query:      No sé bien, algo que valga la pena ver un domingo a la noche, que enganche desde el principio
Reescrita:  Una película de suspense que sigue a un personaje que se ve envuelto en una conspiración criminal. La trama es emocionante y el ritmo acelerado mantiene al espectador enganchado desde el principio.
Pesos:      query=0.7, historial=0.3
Dirección:  similar
  Hidden (Lo oculto) (1989) — 0.7081
  Bowfinger, el pícaro (1999) — 0.6818
  Alone in the Dark (2006) — 0.6771
  Snake Eyes (Ojos de serpiente) (1998) — 0.6726
  Inland Empire (2007) — 0.6594

Mariana (ambiguo)
Query:      Quiero algo distinto a lo de siempre, pero tampoco tan raro, con buenas actuaciones supongo
Reescrita:  Busco una película con actuaciones destacadas que combine elementos de drama y suspense, posiblemente con un enfoque en la corrupción o el crimen, pero sin ser demasiado extrema.
Pesos:      query=0.7, historial=0.3
Dirección:  distinto
  Camino a la gloria (2006) — -0.0685
  Windtalkers (2002) — -0.0630
  Un entrenador de primera (1996) — -0.0570
  Papá por sorpresa (2008) — -0.0519
  Frasier (1993) — -0.0509

Nicolás (ambiguo)
Query:      Algo que pueda ver con amigos o solo, que no sea muy larga ni muy corta
Reescrita:  Una película de acción y comedia que sigue la historia de un grupo de amigos mientras se ven envueltos en una serie de aventuras y desafíos, con un tono ligero y divertido. La película explora temas como amistad y lealtad.
Pesos:      query=0.8, historial=0.2
Dirección:  similar
  Qué les pasa a los hombres (2009) — 0.6351
  Pensamientos mortales (1991) — 0.6328
  Happiness (1998) — 0.6051
  Conociendo a Julia (2004) — 0.6014
  Aquellos maravillosos 70 (2003) — 0.5965

Paula (ambiguo)
Query:      No tengo ganas de pensar mucho, pero tampoco quiero algo vacío, algo intermedio
Reescrita:  Una película que combina elementos de drama y comedia para explorar la vida cotidiana de una persona que busca equilibrio entre la rutina y la libertad. Un género como el drama o la comedia podría ser adecuado.
Pesos:      query=0.4, historial=0.6
Dirección:  similar
  Conociendo a Julia (2004) — 0.7074
  Bowfinger, el pícaro (1999) — 0.7015
  Tránsito (2006) — 0.6993
  Qué les pasa a los hombres (2009) — 0.6970
  Inland Empire (2007) — 0.6965

## Validación

In [50]:
contador_generos = Counter()

for generos_str in df_pelis['genre']:
    generos_str = generos_str.strip('[]')
    generos_list = [g.strip() for g in generos_str.split(',')]
    contador_generos.update(generos_list)

# convertir a DataFrame
df_generos = pd.DataFrame(
    list(contador_generos.items()),
    columns=['Género', 'Frecuencia']
).sort_values('Frecuencia', ascending=False).reset_index(drop=True)

print(df_generos)

             Género  Frecuencia
0             drama        2649
1           comedia        1932
2            acción        1222
3            crimen        1083
4          aventura         944
5           romance         856
6          suspense         740
7            terror         532
8          misterio         479
9          fantasía         412
10         familiar         361
11        animación         351
12  ciencia ficción         347
13        biografía         268
14         historia         151
15           música         148
16          deporte         113
17           bélico         103
18       documental          49
19          musical          37
20            corto          32
21        del oeste          22
22          reality          13
23         concurso           7
24         tertulia           4
25         noticias           2

In [51]:
resultados = []

for idx, usuario in usuarios.iterrows():
    usuario_id = usuario['id']
    generos_usuario = Counter()
    
    for col in ['pelicula_1', 'pelicula_2', 'pelicula_3', 'pelicula_4', 'pelicula_5']:
        nombre_pelicula = usuario[col]
        pelicula = df_pelis[df_pelis['name'] == nombre_pelicula]
        
        if not pelicula.empty:
            generos_str = pelicula.iloc[0]['genre']
            generos_str = generos_str.strip('[]')
            generos_list = [g.strip() for g in generos_str.split(',')]
            generos_usuario.update(generos_list)
    
    # obtener top 3-4 géneros por usuario
    top_generos = generos_usuario.most_common(5)
    generos_str = ', '.join([f"{g} ({f})" for g, f in top_generos])
    
    resultados.append({
        'Usuario': usuario_id,
        'Géneros historial': generos_str
    })

conteo_hist = pd.DataFrame(resultados)
print(conteo_hist.to_string())

   Usuario                                                        Géneros historial
0      U01  suspense (4), drama (3), misterio (3), romance (1), ciencia ficción (1)
1      U02         drama (5), biografía (3), crimen (3), historia (1), misterio (1)
2      U03                                      comedia (5), romance (5), drama (3)
3      U04    ciencia ficción (5), acción (3), drama (2), suspense (2), romance (1)
4      U05         animación (5), aventura (4), drama (2), acción (2), familiar (1)
5      U06             crimen (5), drama (3), comedia (2), acción (1), misterio (1)
6      U07              drama (4), música (3), comedia (3), romance (2), crimen (1)
7      U08          acción (5), aventura (3), crimen (2), suspense (2), comedia (1)
8      U09          drama (5), comedia (3), romance (2), aventura (1), fantasía (1)
9      U10           drama (5), comedia (2), crimen (2), fantasía (1), suspense (1)
10     U11           drama (2), animación (1), aventura (1), acción (1), crimen (1)
11     U12                        comedia (1), romance (1), drama (1), historia (1)
12     U13            drama (4), acción (2), romance (1), aventura (1), comedia (1)
13     U14    comedia (2), drama (2), acción (1), aventura (1), ciencia ficción (1)

In [52]:
for i in range(len(usuarios)):
    print(f"U{i+1}: " + usuarios["query"].iloc[i])

U1: Quiero una película donde una mujer enfrenta una amenaza invisible que viene de alguien cercano
U2: Busco algo basado en hechos reales sobre corrupción o poder político
U3: Una comedia donde la relación entre dos personas empieza de forma ridícula o accidental
U4: Algo que haga pensar sobre qué es real y qué es una construcción, con acción pero también ideas
U5: Animación donde el protagonista lucha por su libertad o identidad en un mundo que lo oprime
U6: Un grupo de personas planea un robo o estafa y las cosas se complican de forma inesperada
U7: Una película sobre músicos o artistas que viven al margen, con mucha atmósfera y estilo visual
U8: Acción directa con un héroe que trabaja solo o casi solo contra una organización criminal o corrupta
U9: Algo tranquilo sobre personas que intentan reconectar o entenderse después de una distancia larga
U10: Algo que sea difícil de clasificar, con una lógica narrativa propia, no convencional
U11: No sé bien, algo que valga la pena ver un domingo a la noche, que enganche desde el principio
U12: Quiero algo distinto a lo de siempre, pero tampoco tan raro, con buenas actuaciones supongo
U13: Algo que pueda ver con amigos o solo, que no sea muy larga ni muy corta
U14: No tengo ganas de pensar mucho, pero tampoco quiero algo vacío, algo intermedio

In [53]:
etiquetas_a_ojo_def = [
    ["suspense", "terror", "drama"],
    ["crimen", "biografía", "historia"],
    ["comedia", "romance", "drama"],
    ["acción", "ciencia ficción", "suspense"],
    ["animación", "drama", "aventura"],
    ["crimen", "acción", "comedia"],
    ["música", "drama", "comedia"],
    ["acción", "crimen", "aventura"],
    ["drama", "romance", "comedia"],
    # el U10 es ambiguo, la etiqueta debe estar mal
]

### Dinámico (LLM)

Evaluamos el enfoque con pesos dinámicos y dirección inferida. Para usuarios con `direccion='distinto'`, los géneros esperados se invierten (queremos que las recomendaciones sean distintas al historial), por lo que la métrica de precisión se interpreta diferente.

In [54]:
resultados_eval_din = []

for user_idx, row in usuarios.head(9).iterrows():
    print(f"\n{'='*70}")
    print(f"{row['nombre']} ({row['tipo_perfil']})")
    print(f"Query: {row['query']}")
    params = parametros_usuarios[user_idx]
    print(f"Pesos: {params['weights']} | Dirección: {params['direccion']}")
    generos_esperados = set(etiquetas_a_ojo_def[user_idx])
    print(f"Géneros Esperados: {', '.join(generos_esperados)}")
    print(f"{'='*70}")

    generos_recomendados = Counter()
    peliculas_buenas = 0
    peliculas_malas = []

    print("\nTop-5 Recomendaciones:")
    for rank, idx in enumerate(top5_indices_dinamico[user_idx], 1):
        pelicula = df_pelis.iloc[idx]
        score = scores_dinamico[user_idx, idx]

        generos_str = pelicula['genre'].strip('[]')
        generos_list = [g.strip() for g in generos_str.split(',')]
        generos_pelicula = set(generos_list)
        generos_recomendados.update(generos_list)

        es_buena = bool(generos_pelicula & generos_esperados)
        if es_buena:
            peliculas_buenas += 1
            marker = "✓"
        else:
            peliculas_malas.append(pelicula['name'])
            marker = "✗"

        print(f"  {rank}. [{marker}] {pelicula['name']} ({int(pelicula['year']) if not pd.isna(pelicula['year']) else 'N/A'}) — {score:.4f}")
        print(f"     Géneros: {', '.join(generos_list)}")

    print(f"\nConteo de Géneros en Recomendaciones:")
    for genero, freq in generos_recomendados.most_common():
        print(f"  {genero}: {freq}")

    generos_capturados = set(generos_recomendados.keys())
    recall = len(generos_capturados & generos_esperados) / len(generos_esperados)
    precision = peliculas_buenas / 5
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    print(f"\nMÉTRICAS:")
    print(f"  Recall (géneros):      {recall:.1%}  ({len(generos_capturados & generos_esperados)}/{len(generos_esperados)})")
    print(f"  Precision (películas): {precision:.1%}  ({peliculas_buenas}/5)")
    print(f"  F1-Score:              {f1:.1%}")

    if peliculas_malas:
        print(f"\nPelículas problemáticas (sin géneros esperados):")
        for pelicula in peliculas_malas:
            print(f"    - {pelicula}")

    resultados_eval_din.append({
        'Usuario': row['nombre'],
        'Recall': recall,
        'Precision': precision,
        'F1': f1,
        'Películas Malas': len(peliculas_malas),
        'Dirección': params['direccion'],
        'Pesos': str(params['weights'])
    })

print(f"\n\n{'='*70}")
print("RESUMEN DE EVALUACIÓN — DINÁMICO")
print(f"{'='*70}")
df_eval_din = pd.DataFrame(resultados_eval_din)
df_eval_din.to_csv('evaluacion_dinamico.csv', index=False)
print(df_eval_din.to_string(index=False))
print(f"\nPromedios:")
print(f"  Recall:    {df_eval_din['Recall'].mean():.1%}")
print(f"  Precision: {df_eval_din['Precision'].mean():.1%}")
print(f"  F1-Score:  {df_eval_din['F1'].mean():.1%}")

======================================================================
Valentina (definido)
Query: Quiero una película donde una mujer enfrenta una amenaza invisible que viene de alguien cercano
Pesos: [0.8, 0.2] | Dirección: similar
Géneros Esperados: suspense, drama, terror
======================================================================

Top-5 Recomendaciones:
  1. [✓] El ente (1983) — 0.7165
     Géneros: drama, terror
  2. [✓] Inland Empire (2007) — 0.7142
     Géneros: drama, fantasía, misterio
  3. [✓] Insectos (2007) — 0.6691
     Géneros: drama, terror, suspense
  4. [✓] Morir todavía (1992) — 0.6641
     Géneros: crimen, drama, misterio
  5. [✓] Nunca hables con extraños (1996) — 0.6637
     Géneros: crimen, drama, romance

Conteo de Géneros en Recomendaciones:
  drama: 5
  terror: 2
  misterio: 2
  crimen: 2
  fantasía: 1
  suspense: 1
  romance: 1

MÉTRICAS:
  Recall (géneros):      100.0%  (3/3)
  Precision (películas): 100.0%  (5/5)
  F1-Score:              100.0%

======================================================================
Rodrigo (definido)
Query: Busco algo basado en hechos reales sobre corrupción o poder político
Pesos: [0.8, 0.2] | Dirección: similar
Géneros Esperados: biografía, crimen, historia
======================================================================

Top-5 Recomendaciones:
  1. [✗] Hidden (Lo oculto) (1989) — 0.7059
     Géneros: terror, ciencia ficción, suspense
  2. [✓] Cliente muerto no paga (1982) — 0.6591
     Géneros: comedia, crimen, misterio
  3. [✗] Alone in the Dark (2006) — 0.6584
     Géneros: acción, terror, ciencia ficción
  4. [✗] Gritos de muerte (2004) — 0.6450
     Géneros: terror, suspense, del oeste
  5. [✗] El jardinero fiel (2005) — 0.6397
     Géneros: drama, misterio, romance

Conteo de Géneros en Recomendaciones:
  terror: 3
  ciencia ficción: 2
  suspense: 2
  misterio: 2
  comedia: 1
  crimen: 1
  acción: 1
  del oeste: 1
  drama: 1
  romance: 1

MÉTRICAS:
  Recall (géneros):      33.3%  (1/3)
  Precision (películas): 20.0%  (1/5)
  F1-Score:              25.0%

Películas problemáticas (sin géneros esperados):
    - Hidden (Lo oculto)
    - Alone in the Dark
    - Gritos de muerte
    - El jardinero fiel

======================================================================
Camila (definido)
Query: Una comedia donde la relación entre dos personas empieza de forma ridícula o accidental
Pesos: [0.8, 0.2] | Dirección: similar
Géneros Esperados: romance, drama, comedia
======================================================================

Top-5 Recomendaciones:
  1. [✓] Happiness (1998) — 0.6861
     Géneros: comedia, drama
  2. [✓] Escuela de novatos (2004) — 0.6812
     Géneros: comedia, crimen, misterio
  3. [✓] Date Movie (2006) — 0.6741
     Géneros: comedia, romance
  4. [✓] Amor loco (1995) — 0.6677
     Géneros: comedia, drama, romance
  5. [✓] Embriagado de amor (2003) — 0.6623
     Géneros: comedia, drama, romance

Conteo de Géneros en Recomendaciones:
  comedia: 5
  drama: 3
  romance: 3
  crimen: 1
  misterio: 1

MÉTRICAS:
  Recall (géneros):      100.0%  (3/3)
  Precision (películas): 100.0%  (5/5)
  F1-Score:              100.0%

======================================================================
Tomás (definido)
Query: Algo que haga pensar sobre qué es real y qué es una construcción, con acción pero también ideas
Pesos: [0.7, 0.3] | Dirección: distinto
Géneros Esperados: suspense, acción, ciencia ficción
======================================================================

Top-5 Recomendaciones:
  1. [✗] Johnny Superstar (1988) — 0.0024
     Géneros: comedia, deporte
  2. [✗] Hum Saath-Saath Hain (1999) — 0.0285
     Géneros: drama, musical
  3. [✗] Camino a la gloria (2006) — 0.0363
     Géneros: biografía, drama, deporte
  4. [✗] Abajo el periscopio (1996) — 0.0395
     Géneros: comedia
  5. [✓] Batalla en Seattle (2008) — 0.0444
     Géneros: acción, drama, historia

Conteo de Géneros en Recomendaciones:
  drama: 3
  comedia: 2
  deporte: 2
  musical: 1
  biografía: 1
  acción: 1
  historia: 1

MÉTRICAS:
  Recall (géneros):      33.3%  (1/3)
  Precision (películas): 20.0%  (1/5)
  F1-Score:              25.0%

Películas problemáticas (sin géneros esperados):
    - Johnny Superstar
    - Hum Saath-Saath Hain
    - Camino a la gloria
    - Abajo el periscopio

======================================================================
Lucía (definido)
Query: Animación donde el protagonista lucha por su libertad o identidad en un mundo que lo oprime
Pesos: [0.8, 0.2] | Dirección: distinto
Géneros Esperados: aventura, drama, animación
======================================================================

Top-5 Recomendaciones:
  1. [✗] Timber Falls (2008) — -0.0515
     Géneros: terror, suspense
  2. [✗] American Pie: ¡Menuda boda! (2003) — -0.0363
     Géneros: comedia
  3. [✓] Rock Star (2001) — 0.0055
     Géneros: drama, música
  4. [✗] Abajo el periscopio (1996) — 0.0315
     Géneros: comedia
  5. [✗] The Beatles Anthology (1995) — 0.0359
     Géneros: documental, música

Conteo de Géneros en Recomendaciones:
  comedia: 2
  música: 2
  terror: 1
  suspense: 1
  drama: 1
  documental: 1

MÉTRICAS:
  Recall (géneros):      33.3%  (1/3)
  Precision (películas): 20.0%  (1/5)
  F1-Score:              25.0%

Películas problemáticas (sin géneros esperados):
    - Timber Falls
    - American Pie: ¡Menuda boda!
    - Abajo el periscopio
    - The Beatles Anthology

======================================================================
Martín (definido)
Query: Un grupo de personas planea un robo o estafa y las cosas se complican de forma inesperada
Pesos: [0.8, 0.2] | Dirección: similar
Géneros Esperados: crimen, acción, comedia
======================================================================

Top-5 Recomendaciones:
  1. [✗] Proyecto Brainstorm (1983) — 0.6197
     Géneros: ciencia ficción, suspense
  2. [✓] Plan oculto (2006) — 0.6147
     Géneros: crimen, drama, misterio
  3. [✓] Máximo riesgo (1993) — 0.5984
     Géneros: acción, aventura, suspense
  4. [✓] Out of sight (Un romance muy peligroso) (1998) — 0.5960
     Géneros: comedia, crimen, drama
  5. [✗] Hidden (Lo oculto) (1989) — 0.5863
     Géneros: terror, ciencia ficción, suspense

Conteo de Géneros en Recomendaciones:
  suspense: 3
  ciencia ficción: 2
  crimen: 2
  drama: 2
  misterio: 1
  acción: 1
  aventura: 1
  comedia: 1
  terror: 1

MÉTRICAS:
  Recall (géneros):      100.0%  (3/3)
  Precision (películas): 60.0%  (3/5)
  F1-Score:              75.0%

Películas problemáticas (sin géneros esperados):
    - Proyecto Brainstorm
    - Hidden (Lo oculto)

======================================================================
Sofía (definido)
Query: Una película sobre músicos o artistas que viven al margen, con mucha atmósfera y estilo visual
Pesos: [0.7, 0.3] | Dirección: similar
Géneros Esperados: drama, comedia, música
======================================================================

Top-5 Recomendaciones:
  1. [✓] Conociendo a Julia (2004) — 0.6770
     Géneros: comedia, drama, romance
  2. [✗] El vagón de la muerte (2008) — 0.6614
     Géneros: terror, misterio, suspense
  3. [✓] Peligrosamente juntos (1986) — 0.6449
     Géneros: comedia, crimen, romance
  4. [✗] Aquarius (1987) — 0.6439
     Géneros: terror, suspense
  5. [✓] Sangre por sangre (1993) — 0.6414
     Géneros: crimen, drama

Conteo de Géneros en Recomendaciones:
  comedia: 2
  drama: 2
  romance: 2
  terror: 2
  suspense: 2
  crimen: 2
  misterio: 1

MÉTRICAS:
  Recall (géneros):      66.7%  (2/3)
  Precision (películas): 60.0%  (3/5)
  F1-Score:              63.2%

Películas problemáticas (sin géneros esperados):
    - El vagón de la muerte
    - Aquarius

======================================================================
Diego (definido)
Query: Acción directa con un héroe que trabaja solo o casi solo contra una organización criminal o corrupta
Pesos: [0.8, 0.2] | Dirección: similar
Géneros Esperados: aventura, crimen, acción
======================================================================

Top-5 Recomendaciones:
  1. [✓] El coche fantástico (N/A) — 0.6913
     Géneros: acción, crimen, drama
  2. [✓] Snake Eyes (Ojos de serpiente) (1998) — 0.6780
     Géneros: crimen, misterio, suspense
  3. [✓] Daredevil (2003) — 0.6755
     Géneros: acción, crimen
  4. [✓] Open Range (2003) — 0.6598
     Géneros: acción, drama, romance
  5. [✓] El poder del talismán (2003) — 0.6551
     Géneros: acción, comedia, fantasía

Conteo de Géneros en Recomendaciones:
  acción: 4
  crimen: 3
  drama: 2
  misterio: 1
  suspense: 1
  romance: 1
  comedia: 1
  fantasía: 1

MÉTRICAS:
  Recall (géneros):      66.7%  (2/3)
  Precision (películas): 100.0%  (5/5)
  F1-Score:              80.0%

======================================================================
Elena (definido)
Query: Algo tranquilo sobre personas que intentan reconectar o entenderse después de una distancia larga
Pesos: [0.7, 0.3] | Dirección: similar
Géneros Esperados: drama, romance, comedia
======================================================================

Top-5 Recomendaciones:
  1. [✓] El juego del amor (2007) — 0.7259
     Géneros: drama, romance
  2. [✓] It's All About Love (Todo es por amor) (2003) — 0.7008
     Géneros: drama, romance, ciencia ficción
  3. [✓] Timecode (2000) — 0.6864
     Géneros: drama, romance
  4. [✓] El sueño de una noche de verano, de William Shakespeare (1999) — 0.6861
     Géneros: comedia, fantasía, romance
  5. [✓] El diario de Noa (2004) — 0.6823
     Géneros: drama, romance

Conteo de Géneros en Recomendaciones:
  romance: 5
  drama: 4
  ciencia ficción: 1
  comedia: 1
  fantasía: 1

MÉTRICAS:
  Recall (géneros):      100.0%  (3/3)
  Precision (películas): 100.0%  (5/5)
  F1-Score:              100.0%


======================================================================
RESUMEN DE EVALUACIÓN — DINÁMICO
======================================================================
  Usuario   Recall  Precision       F1  Películas Malas Dirección      Pesos
Valentina 1.000000        1.0 1.000000                0   similar [0.8, 0.2]
  Rodrigo 0.333333        0.2 0.250000                4   similar [0.8, 0.2]
   Camila 1.000000        1.0 1.000000                0   similar [0.8, 0.2]
    Tomás 0.333333        0.2 0.250000                4  distinto [0.7, 0.3]
    Lucía 0.333333        0.2 0.250000                4  distinto [0.8, 0.2]
   Martín 1.000000        0.6 0.750000                2   similar [0.8, 0.2]
    Sofía 0.666667        0.6 0.631579                2   similar [0.7, 0.3]
    Diego 0.666667        1.0 0.800000                0   similar [0.8, 0.2]
    Elena 1.000000        1.0 1.000000                0   similar [0.7, 0.3]

Promedios:
  Recall:    70.4%
  Precision: 64.4%
  F1-Score:  65.9%

## AGREGAR CONCLUSIONES